[[Infernal]]
arch = "i686"
git-tree-sha1 = "3d361216ae4167a5c4a4728506610fc11e17bd40"
libc = "glibc"
os = "linux"

    [[Infernal.download]]
    sha256 = "2d112eb6dd4d044e8aabde5cb789d7a0d3f4fb18b7c0e2aca2407453baf083c9"
    url = "https://github.com/JuliaBinaryWrappers/Infernal_jll.jl/releases/download/Infernal-v1.1.4+0/Infernal.v1.1.4.i686-linux-gnu.tar.gz"
[[Infernal]]
arch = "i686"
git-tree-sha1 = "afc73b6dcf46600bcfdfc1ace4fe380671df0a52"
libc = "musl"
os = "linux"

    [[Infernal.download]]
    sha256 = "1f8d440b8bb5d0561dde243b4b81fd963cf2ad82b68012f471fd09d169977b64"
    url = "https://github.com/JuliaBinaryWrappers/Infernal_jll.jl/releases/download/Infernal-v1.1.4+0/Infernal.v1.1.4.i686-linux-musl.tar.gz"
[[Infernal]]
arch = "x86_64"
git-tree-sha1 = "250c353e0f58ca0f0a43d2bb23d9ad98ed5046ac"
os = "macos"

    [[Infernal.download]]
    sha256 = "f2bf7e4ecf1b252c8796523b57c2947fbd8109d655da628902bf821cf1d8fa8c"
    url = "https://github.com/JuliaBinaryWrappers/Infernal_jll.jl/releases/download/Infernal-v1.1.4+0/Infernal.v1.1.4.x86_64-apple-darwin.tar.gz"
[[Infernal]]
arch = "x86_64"
git-tree-sha1 = "d99b9810f3da8592b91b2d14e888623bc00cc351"
libc = "glibc"
os = "linux"

    [[Infernal.download]]
    sha256 = "ef2a9f4e5855b910edd986673aaa29a56d5acd608eb06a69929720b815571a83"
    url = "https://github.com/JuliaBinaryWrappers/Infernal_jll.jl/releases/download/Infernal-v1.1.4+0/Infernal.v1.1.4.x86_64-linux-gnu.tar.gz"
[[Infernal]]
arch = "x86_64"
git-tree-sha1 = "9fbae7d1787229274a995c5abe0db9a805779ee9"
libc = "musl"
os = "linux"

    [[Infernal.download]]
    sha256 = "b688de8b27be11f0cae2517f74a2cd35627fb980caf04afad9fb5f7e885954b0"
    url = "https://github.com/JuliaBinaryWrappers/Infernal_jll.jl/releases/download/Infernal-v1.1.4+0/Infernal.v1.1.4.x86_64-linux-musl.tar.gz"
[[Infernal]]
arch = "x86_64"
git-tree-sha1 = "0b6298a17f5523e79e17b02dcfd236519d5860e8"
os = "freebsd"

    [[Infernal.download]]
    sha256 = "85359a4ef3f476f396232ee5012ba0b4d7d5b050e6c937cb67df504052d2f902"
    url = "https://github.com/JuliaBinaryWrappers/Infernal_jll.jl/releases/download/Infernal-v1.1.4+0/Infernal.v1.1.4.x86_64-unknown-freebsd.tar.gz"
