# Autogenerated wrapper script for Infernal_jll for i686-linux-musl
export cmalign, cmbuild, cmcalibrate, cmconvert, cmemit, cmfetch, cmpress, cmscan, cmsearch, cmstat, easel, esl_afetch, esl_alimanip, esl_alimap, esl_alimask, esl_alimerge, esl_alipid, esl_alirev, esl_alistat, esl_compalign, esl_compstruct, esl_construct, esl_histplot, esl_mask, esl_mixdchlet, esl_reformat, esl_selectn, esl_seqrange, esl_seqstat, esl_sfetch, esl_shuffle, esl_ssdraw, esl_translate, esl_weight

using GSL_jll
JLLWrappers.@generate_wrapper_header("Infernal")
JLLWrappers.@declare_executable_product(cmalign)
JLLWrappers.@declare_executable_product(cmbuild)
JLLWrappers.@declare_executable_product(cmcalibrate)
JLLWrappers.@declare_executable_product(cmconvert)
JLLWrappers.@declare_executable_product(cmemit)
JLLWrappers.@declare_executable_product(cmfetch)
JLLWrappers.@declare_executable_product(cmpress)
JLLWrappers.@declare_executable_product(cmscan)
JLLWrappers.@declare_executable_product(cmsearch)
JLLWrappers.@declare_executable_product(cmstat)
JLLWrappers.@declare_executable_product(easel)
JLLWrappers.@declare_executable_product(esl_afetch)
JLLWrappers.@declare_executable_product(esl_alimanip)
JLLWrappers.@declare_executable_product(esl_alimap)
JLLWrappers.@declare_executable_product(esl_alimask)
JLLWrappers.@declare_executable_product(esl_alimerge)
JLLWrappers.@declare_executable_product(esl_alipid)
JLLWrappers.@declare_executable_product(esl_alirev)
JLLWrappers.@declare_executable_product(esl_alistat)
JLLWrappers.@declare_executable_product(esl_compalign)
JLLWrappers.@declare_executable_product(esl_compstruct)
JLLWrappers.@declare_executable_product(esl_construct)
JLLWrappers.@declare_executable_product(esl_histplot)
JLLWrappers.@declare_executable_product(esl_mask)
JLLWrappers.@declare_executable_product(esl_mixdchlet)
JLLWrappers.@declare_executable_product(esl_reformat)
JLLWrappers.@declare_executable_product(esl_selectn)
JLLWrappers.@declare_executable_product(esl_seqrange)
JLLWrappers.@declare_executable_product(esl_seqstat)
JLLWrappers.@declare_executable_product(esl_sfetch)
JLLWrappers.@declare_executable_product(esl_shuffle)
JLLWrappers.@declare_executable_product(esl_ssdraw)
JLLWrappers.@declare_executable_product(esl_translate)
JLLWrappers.@declare_executable_product(esl_weight)
function __init__()
    JLLWrappers.@generate_init_header(GSL_jll)
    JLLWrappers.@init_executable_product(
        cmalign,
        "bin/cmalign",
    )

    JLLWrappers.@init_executable_product(
        cmbuild,
        "bin/cmbuild",
    )

    JLLWrappers.@init_executable_product(
        cmcalibrate,
        "bin/cmcalibrate",
    )

    JLLWrappers.@init_executable_product(
        cmconvert,
        "bin/cmconvert",
    )

    JLLWrappers.@init_executable_product(
        cmemit,
        "bin/cmemit",
    )

    JLLWrappers.@init_executable_product(
        cmfetch,
        "bin/cmfetch",
    )

    JLLWrappers.@init_executable_product(
        cmpress,
        "bin/cmpress",
    )

    JLLWrappers.@init_executable_product(
        cmscan,
        "bin/cmscan",
    )

    JLLWrappers.@init_executable_product(
        cmsearch,
        "bin/cmsearch",
    )

    JLLWrappers.@init_executable_product(
        cmstat,
        "bin/cmstat",
    )

    JLLWrappers.@init_executable_product(
        easel,
        "bin/easel",
    )

    JLLWrappers.@init_executable_product(
        esl_afetch,
        "bin/esl-afetch",
    )

    JLLWrappers.@init_executable_product(
        esl_alimanip,
        "bin/esl-alimanip",
    )

    JLLWrappers.@init_executable_product(
        esl_alimap,
        "bin/esl-alimap",
    )

    JLLWrappers.@init_executable_product(
        esl_alimask,
        "bin/esl-alimask",
    )

    JLLWrappers.@init_executable_product(
        esl_alimerge,
        "bin/esl-alimerge",
    )

    JLLWrappers.@init_executable_product(
        esl_alipid,
        "bin/esl-alipid",
    )

    JLLWrappers.@init_executable_product(
        esl_alirev,
        "bin/esl-alirev",
    )

    JLLWrappers.@init_executable_product(
        esl_alistat,
        "bin/esl-alistat",
    )

    JLLWrappers.@init_executable_product(
        esl_compalign,
        "bin/esl-compalign",
    )

    JLLWrappers.@init_executable_product(
        esl_compstruct,
        "bin/esl-compstruct",
    )

    JLLWrappers.@init_executable_product(
        esl_construct,
        "bin/esl-construct",
    )

    JLLWrappers.@init_executable_product(
        esl_histplot,
        "bin/esl-histplot",
    )

    JLLWrappers.@init_executable_product(
        esl_mask,
        "bin/esl-mask",
    )

    JLLWrappers.@init_executable_product(
        esl_mixdchlet,
        "bin/esl-mixdchlet",
    )

    JLLWrappers.@init_executable_product(
        esl_reformat,
        "bin/esl-reformat",
    )

    JLLWrappers.@init_executable_product(
        esl_selectn,
        "bin/esl-selectn",
    )

    JLLWrappers.@init_executable_product(
        esl_seqrange,
        "bin/esl-seqrange",
    )

    JLLWrappers.@init_executable_product(
        esl_seqstat,
        "bin/esl-seqstat",
    )

    JLLWrappers.@init_executable_product(
        esl_sfetch,
        "bin/esl-sfetch",
    )

    JLLWrappers.@init_executable_product(
        esl_shuffle,
        "bin/esl-shuffle",
    )

    JLLWrappers.@init_executable_product(
        esl_ssdraw,
        "bin/esl-ssdraw",
    )

    JLLWrappers.@init_executable_product(
        esl_translate,
        "bin/esl-translate",
    )

    JLLWrappers.@init_executable_product(
        esl_weight,
        "bin/esl-weight",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
